name: Test

on:
  - pull_request
  - push

env:
  BUNDLE_WITHOUT: release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
        puppet:
          - "~> 8.0"
          - "~> 7.0"
        exclude:
          - ruby: "2.7"
            puppet: "~> 8.0"

    name: "Ruby ${{ matrix.ruby }} - Puppet ${{ matrix.puppet }}"
    env:
      PUPPET_VERSION: ${{ matrix.puppet }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
      - name: Rubocop
        run: bundle exec rake rubocop
      - name: Lint
        run: bundle exec rake lint
  acceptance:
    runs-on: ubuntu-latest
    env:
      BEAKER_setfile: ${{ matrix.beaker }}
    strategy:
      fail-fast: false
      matrix:
        beaker:
          - centos9-64a
          - debian11-64a
    name: Acceptance / Image ${{ matrix.beaker }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Run acceptance
        run: bundle exec rake beaker
